# Generated by Django 5.1.3 on 2025-01-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
