# Generated by Django 5.1.3 on 2025-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0002_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
