# Generated by Django 5.1.3 on 2025-01-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0003_alter_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(),
        ),
    ]
