# Generated by Django 5.1.4 on 2025-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0005_estadistica_mesa_factura_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesero',
            old_name='pedidosAtentidos',
            new_name='pedidosAtendidos',
        ),
        migrations.AddField(
            model_name='estadistica_mesero',
            name='pedidosAtendidos',
            field=models.IntegerField(null=True),
        ),
    ]
