# Generated by Django 5.1.4 on 2025-01-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0006_rename_pedidosatentidos_mesero_pedidosatendidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica_mesero',
            name='pedidosAtendidos',
        ),
    ]
