# Generated by Django 5.1.4 on 2025-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='impuesto_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
