# Generated by Django 5.1.4 on 2025-01-11 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0002_alter_factura_impuesto_total_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_efectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacionApp.pagoefectivo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacionApp.pagotarjeta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacionApp.pagotransferencia'),
        ),
        migrations.AddField(
            model_name='factura',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacionApp.promocion'),
        ),
    ]
