# Generated by Django 5.1.4 on 2025-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0003_factura_metodo_pago_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
