# Generated by Django 5.1.4 on 2025-01-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0005_impuesto_producto_impuestos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacionApp.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionApp.producto')),
            ],
        ),
    ]
