# Generated by Django 5.1.4 on 2025-01-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0006_itemfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
